version: "3"

services:
  api:
    image: ruby:3.4-alpine
    environment:
      # Setting the response body as an environment variable is just a way
      # to get around the multiple layers of nested quotes in the command!
      RESPONSE_BODY: "{\"id\": \"1\", \"name\": \"Foo\"}"
    command: sh -c "gem install webrick -v 1.8.1 && gem install rack -v 2.2.7 && rackup -o 0.0.0.0 -b \"run ->(env){ [200, {'Content-Type' => 'application/json'}, [ENV['RESPONSE_BODY']]] }\""
    expose:
      - "9292"

  pact_verifier:
    image: pactfoundation/pact-cli:0.56.0-pactcli0.56.0
    depends_on:
      - api
    environment:
      - PACT_BROKER_BASE_URL
      - PACT_BROKER_USERNAME
      - PACT_BROKER_PASSWORD
      - PACT_BROKER_PUBLISH_VERIFICATION_RESULTS
      - GIT_COMMIT
      - GIT_BRANCH
    command: >
      verify
      --provider-base-url http://api:9292
      --provider docker-example-provider
      --provider-app-version ${GIT_COMMIT}
      --provider-version-tag ${GIT_BRANCH}
      --wait 20