FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

ENV NOKOGIRI_USE_SYSTEM_LIBRARIES=1
ENV BUNDLE_SILENCE_ROOT_WARNING=1

ADD docker/gemrc /root/.gemrc

RUN apk update \
  && apk add ruby \
             ruby-bundler \
             ruby-io-console \
             ca-certificates \
             libressl \
             less \
             git \
  && apk add --virtual build-dependencies \
             build-base \
             ruby-dev \
             libressl-dev \
             ruby-rdoc \
  && bundle config build.nokogiri --use-system-libraries \
  && bundle config git.allow_insecure true \
  && gem update --system 4.0.16 \
  && gem install json \
  && gem install bigdecimal \
  && gem install racc \
  && gem install io-console \
  && gem uninstall rubygems-update

ENV HOME=/pact
ENV DOCKER=true
WORKDIR $HOME

ADD pact-cli.gemspec Gemfile Gemfile.lock $HOME/
ADD lib/pact/cli/version.rb $HOME/lib/pact/cli/version.rb
RUN bundle config set without 'test development' \
    bundle config set deployment 'true' \
      && bundle install
