name: Audit

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 4 # Midnight Wednesday

jobs:
  audit:
    name: 👮 audit
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    env:
      TAG: latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Docker multi-arch builder for ${{ matrix.DOCKER_TARGET_PLATFORM }}
        if: ${{ matrix.DOCKER_TARGET_PLATFORM }} == 'linux/arm64'
        run: ./script/release-workflow/docker-prepare.sh
      - name: Audit Docker image for ${{ matrix.DOCKER_TARGET_PLATFORM }}
        run: ./script/release-workflow/audit.sh
        env:
          DOCKER_TARGET_PLATFORM: linux/arm64
