name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    env:
      DOCKER_IMAGE_ORG_AND_NAME: pactfoundation/pact-cli
    steps:
      - uses: actions/checkout@v4

      - name: Integration tests
        run: script/test.sh

      - name: Scan
        run: script/scan.sh pactfoundation/pact-cli

  test-node:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v4


      - name: Login to Docker Hub
        run: script/release-workflow/docker-login.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Integration tests
        run: script/test-node.sh
        env:
          NODE_VERSION: ${{ matrix.node }}

      - name: Scan
        run: script/scan.sh pactfoundation/pact-cli:latest-node${{ matrix.node }}
