name: Update gems

on:
  repository_dispatch:
    types:
      - gem-released
  workflow_dispatch:

jobs:
  update-gems:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ruby/setup-ruby@v1

    - name: Configure git
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global push.default current

    - id: update
      run: script/workflows/update.sh
      env:
        RELEASED_GEM_NAME: ${{ github.event.client_payload.name }}
        RELEASED_GEM_VERSION: ${{ github.event.client_payload.version }}
  
    - name: Commit and push gem file changes
      run: script/workflows/git-commit-and-push-gemfile.sh
      env:
        COMMIT_MESSAGE: ${{ steps.update.outputs.commit_message }}
  
    - name: Trigger release
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GHTOKENFORPACTCLIRELEASE }}
        event-type: release-triggered
